/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  /*   tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['intro'],
    },


  ],
  */
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Hooks',
      items: [
        {
          type: 'autogenerated',
          dirName: 'react/hooks', // Generate sidebar slice from docs/tutorials/easy
        },
      ],
    },
    {
      type: 'category',
      label: 'Linting',
      items: [
        {
          type: 'autogenerated',
          dirName: 'react/lint', // Generate sidebar slice from docs/tutorials/easy
        },
      ],
    },
    {
      type: 'category',
      label: 'UI',
      items: [
        {
          type: 'autogenerated',
          dirName: 'react/ui', // Generate sidebar slice from docs/tutorials/easy
        },
      ],
    },
    {
      type: 'category',
      label: 'Array Map',
      items: ['react/array-map'],
    },
    {
      type: 'category',
      label: 'CLI-tools',
      items: [
        {
          type: 'autogenerated',
          dirName: 'react/cli-tools', // Generate sidebar slice from docs/tutorials/easy
        },
      ],
    },
    {
      type: 'category',
      label: 'Typescript',
      items: [
        {
          type: 'autogenerated',
          dirName: 'react/typescript', // Generate sidebar slice from docs/tutorials/easy
        },
      ],
    },
    {
      type: 'category',
      label: 'Typescript',
      items: [
        {
          type: 'autogenerated',
          dirName: 'react', // Generate sidebar slice from docs/tutorials/easy
        },
      ],
    },
  ],

  apiSidebar: [
    {
      type: 'category',
      label: 'General',
      items: [
        {
          type: 'autogenerated',
          dirName: 'javascript', // Generate sidebar slice from docs/tutorials/easy
        },
      ],
    },
  
  ],
}

module.exports = sidebars
